import { DashboardStats, Product, User, Order, Coupon, AnalyticsData, AIInsight } from '@/types/dashboard';
import { addDays, subDays, format } from 'date-fns';

// Mock Dashboard Stats
export const mockStats: DashboardStats = {
  totalOrders: 12847,
  totalUsers: 8394,
  totalRevenue: 284750,
  totalRefunds: 3245,
  ordersGrowth: 12.5,
  usersGrowth: 8.2,
  revenueGrowth: 15.3,
  refundsGrowth: -5.8,
};

// Mock Products
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    description: 'Premium noise-cancelling wireless headphones with 30-hour battery life',
    price: 159.99,
    originalPrice: 199.99,
    discount: 20,
    category: 'Electronics',
    stock: 45,
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=300',
    status: 'active',
    createdAt: subDays(new Date(), 30),
    updatedAt: subDays(new Date(), 2),
    sales: 1234,
    rating: 4.8,
    reviewCount: 256,
  },
  {
    id: '2',
    name: 'Smart Fitness Watch',
    description: 'Advanced fitness tracker with heart rate monitoring and GPS',
    price: 249.99,
    category: 'Wearables',
    stock: 23,
    image: 'https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg?auto=compress&cs=tinysrgb&w=300',
    status: 'active',
    createdAt: subDays(new Date(), 25),
    updatedAt: subDays(new Date(), 1),
    sales: 892,
    rating: 4.6,
    reviewCount: 143,
  },
  {
    id: '3',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable and sustainable organic cotton t-shirt',
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    category: 'Clothing',
    stock: 78,
    image: 'https://images.pexels.com/photos/1020585/pexels-photo-1020585.jpeg?auto=compress&cs=tinysrgb&w=300',
    status: 'active',
    createdAt: subDays(new Date(), 20),
    updatedAt: subDays(new Date(), 3),
    sales: 567,
    rating: 4.4,
    reviewCount: 89,
  },
  {
    id: '4',
    name: 'Premium Coffee Beans',
    description: 'Single-origin Arabica coffee beans, medium roast',
    price: 24.99,
    category: 'Food & Beverage',
    stock: 156,
    image: 'https://images.pexels.com/photos/894695/pexels-photo-894695.jpeg?auto=compress&cs=tinysrgb&w=300',
    status: 'active',
    createdAt: subDays(new Date(), 15),
    updatedAt: subDays(new Date(), 1),
    sales: 743,
    rating: 4.9,
    reviewCount: 198,
  },
  {
    id: '5',
    name: 'Yoga Mat Pro',
    description: 'Non-slip premium yoga mat with alignment lines',
    price: 79.99,
    category: 'Sports & Fitness',
    stock: 34,
    image: 'https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg?auto=compress&cs=tinysrgb&w=300',
    status: 'active',
    createdAt: subDays(new Date(), 10),
    updatedAt: new Date(),
    sales: 321,
    rating: 4.7,
    reviewCount: 67,
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice.johnson@email.com',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    role: 'customer',
    status: 'active',
    registrationDate: subDays(new Date(), 120),
    lastLogin: subDays(new Date(), 1),
    totalOrders: 15,
    totalSpent: 1247.85,
    location: 'New York, USA',
    segment: 'premium',
  },
  {
    id: '2',
    name: 'Bob Smith',
    email: 'bob.smith@email.com',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150',
    role: 'customer',
    status: 'active',
    registrationDate: subDays(new Date(), 90),
    lastLogin: subDays(new Date(), 3),
    totalOrders: 8,
    totalSpent: 567.42,
    location: 'California, USA',
    segment: 'regular',
  },
  {
    id: '3',
    name: 'Carol Davis',
    email: 'carol.davis@email.com',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150',
    role: 'admin',
    status: 'active',
    registrationDate: subDays(new Date(), 365),
    lastLogin: new Date(),
    totalOrders: 0,
    totalSpent: 0,
    location: 'Texas, USA',
    segment: 'regular',
  },
  {
    id: '4',
    name: 'David Wilson',
    email: 'david.wilson@email.com',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
    role: 'customer',
    status: 'active',
    registrationDate: subDays(new Date(), 30),
    lastLogin: subDays(new Date(), 7),
    totalOrders: 3,
    totalSpent: 189.97,
    location: 'Florida, USA',
    segment: 'new',
  },
];

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: '1',
    userName: 'Alice Johnson',
    userEmail: 'alice.johnson@email.com',
    items: [
      {
        productId: '1',
        productName: 'Wireless Bluetooth Headphones',
        productImage: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=150',
        quantity: 1,
        price: 159.99,
      },
      {
        productId: '3',
        productName: 'Organic Cotton T-Shirt',
        productImage: 'https://images.pexels.com/photos/1020585/pexels-photo-1020585.jpeg?auto=compress&cs=tinysrgb&w=150',
        quantity: 2,
        price: 29.99,
      },
    ],
    total: 219.97,
    status: 'delivered',
    createdAt: subDays(new Date(), 5),
    updatedAt: subDays(new Date(), 1),
    shippingAddress: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
    paymentMethod: 'Credit Card',
    trackingNumber: 'TRK123456789',
  },
  {
    id: 'ORD-002',
    userId: '2',
    userName: 'Bob Smith',
    userEmail: 'bob.smith@email.com',
    items: [
      {
        productId: '2',
        productName: 'Smart Fitness Watch',
        productImage: 'https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg?auto=compress&cs=tinysrgb&w=150',
        quantity: 1,
        price: 249.99,
      },
    ],
    total: 249.99,
    status: 'shipped',
    createdAt: subDays(new Date(), 3),
    updatedAt: subDays(new Date(), 1),
    shippingAddress: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90210',
      country: 'USA',
    },
    paymentMethod: 'PayPal',
    trackingNumber: 'TRK987654321',
  },
  {
    id: 'ORD-003',
    userId: '4',
    userName: 'David Wilson',
    userEmail: 'david.wilson@email.com',
    items: [
      {
        productId: '4',
        productName: 'Premium Coffee Beans',
        productImage: 'https://images.pexels.com/photos/894695/pexels-photo-894695.jpeg?auto=compress&cs=tinysrgb&w=150',
        quantity: 3,
        price: 24.99,
      },
    ],
    total: 74.97,
    status: 'processing',
    createdAt: subDays(new Date(), 1),
    updatedAt: new Date(),
    shippingAddress: {
      street: '789 Pine Rd',
      city: 'Miami',
      state: 'FL',
      zipCode: '33101',
      country: 'USA',
    },
    paymentMethod: 'Credit Card',
  },
];

// Mock Coupons
export const mockCoupons: Coupon[] = [
  {
    id: '1',
    code: 'WELCOME20',
    description: 'Welcome discount for new customers',
    type: 'percentage',
    value: 20,
    minimumAmount: 50,
    usageLimit: 1000,
    usedCount: 234,
    expirationDate: addDays(new Date(), 30),
    status: 'active',
    createdAt: subDays(new Date(), 60),
  },
  {
    id: '2',
    code: 'SUMMER50',
    description: 'Summer special - $50 off',
    type: 'fixed',
    value: 50,
    minimumAmount: 200,
    maximumDiscount: 50,
    usageLimit: 500,
    usedCount: 123,
    expirationDate: addDays(new Date(), 15),
    status: 'active',
    applicableCategories: ['Clothing', 'Sports & Fitness'],
    createdAt: subDays(new Date(), 45),
  },
  {
    id: '3',
    code: 'ELECTRONICS15',
    description: '15% off all electronics',
    type: 'percentage',
    value: 15,
    usageLimit: 200,
    usedCount: 67,
    expirationDate: addDays(new Date(), 7),
    status: 'active',
    applicableCategories: ['Electronics'],
    createdAt: subDays(new Date(), 30),
  },
];

// Mock Analytics Data
export const mockAnalytics: AnalyticsData = {
  salesTrend: Array.from({ length: 30 }, (_, i) => ({
    date: format(subDays(new Date(), 29 - i), 'MMM dd'),
    sales: Math.floor(Math.random() * 5000) + 2000,
    orders: Math.floor(Math.random() * 100) + 50,
  })),
  revenueByCategory: [
    { category: 'Electronics', revenue: 125000, percentage: 35 },
    { category: 'Clothing', revenue: 89000, percentage: 25 },
    { category: 'Food & Beverage', revenue: 67000, percentage: 19 },
    { category: 'Sports & Fitness', revenue: 45000, percentage: 13 },
    { category: 'Wearables', revenue: 28000, percentage: 8 },
  ],
  userGrowth: Array.from({ length: 12 }, (_, i) => ({
    month: format(subDays(new Date(), (11 - i) * 30), 'MMM'),
    newUsers: Math.floor(Math.random() * 500) + 200,
    activeUsers: Math.floor(Math.random() * 2000) + 1000,
  })),
  topProducts: mockProducts.slice(0, 5).map(product => ({
    id: product.id,
    name: product.name,
    sales: product.sales,
    revenue: product.sales * product.price,
  })),
};

// Mock AI Insights
export const mockAIInsights: AIInsight[] = [
  {
    id: '1',
    type: 'recommendation',
    title: 'Optimize Wireless Headphones Pricing',
    description: 'Based on market analysis, increasing the price by 8% could boost revenue by 12% without significantly impacting demand.',
    impact: 'high',
    category: 'sales',
    actionable: true,
    createdAt: subDays(new Date(), 1),
    data: { currentPrice: 159.99, suggestedPrice: 172.79, expectedRevenue: 186540 },
  },
  {
    id: '2',
    type: 'alert',
    title: 'Low Stock Alert: Smart Fitness Watch',
    description: 'Stock levels for Smart Fitness Watch are critically low (23 units). Reorder recommended to avoid stockouts.',
    impact: 'high',
    category: 'inventory',
    actionable: true,
    createdAt: subDays(new Date(), 2),
    data: { currentStock: 23, recommendedOrder: 100, avgMonthlySales: 89 },
  },
  {
    id: '3',
    type: 'prediction',
    title: 'Seasonal Demand Spike Expected',
    description: 'Coffee products typically see 35% increase in sales during winter months. Consider increasing inventory.',
    impact: 'medium',
    category: 'inventory',
    actionable: true,
    createdAt: subDays(new Date(), 3),
    data: { category: 'Food & Beverage', expectedIncrease: 35, timeframe: 'Nov-Feb' },
  },
  {
    id: '4',
    type: 'optimization',
    title: 'Email Campaign Opportunity',
    description: 'Users who viewed Yoga Mat Pro but didn\'t purchase show 78% conversion rate with targeted email campaigns.',
    impact: 'medium',
    category: 'marketing',
    actionable: true,
    createdAt: subDays(new Date(), 4),
    data: { targetUsers: 145, expectedConversion: 78, potentialRevenue: 8969 },
  },
];

// Sparkline data for dashboard cards
export const generateSparklineData = (days: number = 7) => {
  return Array.from({ length: days }, (_, i) => ({
    date: subDays(new Date(), days - 1 - i),
    value: Math.floor(Math.random() * 100) + 50,
  }));
};